-- Geo-linked detail types: DISTRICT / NEIGHBORHOOD selects sourced from the geographic DB.
ALTER TABLE `Attribute`
  MODIFY `type` ENUM(
    'TEXT','TEXTAREA','NUMBER','BOOLEAN','SELECT','MULTI_SELECT','DATE','PHOTOS','DOCUMENTS',
    'URL','PHONE','DATE_FULL','MONEY','MONEY_THOUSANDS','AREA_ORIGINAL','AREA_ALLOCATED','YESNO',
    'DISTRICT','NEIGHBORHOOD'
  ) NOT NULL;
