#!/usr/bin/env bash
# Cloudflare hardening step B3 — make the origin refuse non-Cloudflare traffic on the APEX
# HTTPS vhosts, so a scraper can't bypass the WAF / rate limits by hitting 77.42.66.76 directly.
#
#   bash ops/cloudflare-lockdown.sh on      # apply (regenerates the allow-list first)
#   bash ops/cloudflare-lockdown.sh off     # remove (instant, one reload)
#   bash ops/cloudflare-lockdown.sh status
#
# ⚠️ READ BEFORE ENABLING — this CHANGES THE CLOUDFLARE ROLLBACK PROCEDURE.
#    Normally rolling Cloudflare back = grey-cloud the DNS record. With B3 on, grey-clouding
#    sends visitors straight to an origin that now answers 403. **Rollback is therefore TWO
#    steps: run `cloudflare-lockdown.sh off` FIRST, then grey-cloud.** Getting that order wrong
#    is a self-inflicted outage.
#
# What it deliberately does NOT touch:
#  - the `www.*` :443 vhosts — those are still DNS-only (grey) as of 2026-07-22, so restricting
#    them would 403 real visitors who type "www.". They only `return 301` to the apex anyway, so
#    a direct hit there leaks no content.
#  - the :80 vhosts — they serve /.well-known/acme-challenge/ for Let's Encrypt renewal and
#    otherwise just redirect. Keeping :80 open preserves cert renewal even if Cloudflare is off.
#  - CWP's own vhosts (webmail.noc / mail.noc / cpanel.noc / the bare-IP vhost). Restricting
#    those would lock the owner out of webmail and the control panel.
set -euo pipefail

CONF=/etc/nginx/conf.d/noc.conf
INC=/etc/nginx/cloudflare-allow.inc
ORIGIN_IP=77.42.66.76
MARK='cf-lockdown'

reload_or_revert() {
  local backup="$1"
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx
    return 0
  fi
  echo "nginx -t FAILED — reverting $CONF" >&2
  cp -a "$backup" "$CONF"
  nginx -t >/dev/null 2>&1 && systemctl reload nginx
  return 1
}

case "${1:-status}" in
  on)
    # Regenerate the allow-list from Cloudflare's published ranges every time, so an enable is
    # never applied against a stale list. (curl output lacks a trailing newline — hence the echo.)
    {
      echo "# Generated by ops/cloudflare-lockdown.sh — do not edit by hand."
      { curl -fsS https://www.cloudflare.com/ips-v4; echo; curl -fsS https://www.cloudflare.com/ips-v6; echo; } \
        | grep -v '^$' | sed 's/^/allow /; s/$/;/'
      echo "allow 127.0.0.1;      # the box itself"
      echo "allow ${ORIGIN_IP};   # the origin's own public IP (loopback-via-public-IP checks)"
      echo "deny all;"
    } > "$INC"
    chmod 644 "$INC"
    echo "allow-list: $(grep -c '^allow ' "$INC") entries"

    if grep -q "$MARK" "$CONF"; then
      echo "already on (re-generated the allow-list); reloading"
      systemctl reload nginx
      exit 0
    fi
    BAK="${CONF}.bak-lockdown-$(date -u +%Y%m%dT%H%M%SZ)"
    cp -a "$CONF" "$BAK"
    # `client_max_body_size 35m;` appears ONCE in each of the two apex :443 blocks and nowhere
    # else in this file — which is exactly the pair we want to restrict.
    sed -i "s|^\(    client_max_body_size 35m;\)\$|\1\n    include ${INC}; # ${MARK}|" "$CONF"
    n=$(grep -c "$MARK" "$CONF" || true)
    if [ "$n" -ne 2 ]; then
      echo "expected 2 insertion points, got $n — reverting, nothing changed" >&2
      cp -a "$BAK" "$CONF"; exit 1
    fi
    reload_or_revert "$BAK" && echo "B3 ON — apex :443 now accepts Cloudflare only (backup: $BAK)"
    ;;

  off)
    BAK="${CONF}.bak-unlock-$(date -u +%Y%m%dT%H%M%SZ)"
    cp -a "$CONF" "$BAK"
    sed -i "/${MARK}/d" "$CONF"
    reload_or_revert "$BAK" && echo "B3 OFF — origin reachable directly again (backup: $BAK)"
    ;;

  status)
    if grep -q "$MARK" "$CONF" 2>/dev/null; then
      echo "B3: ON ($(grep -c "$MARK" "$CONF") vhost(s) restricted, $(grep -c '^allow ' "$INC" 2>/dev/null || echo 0) allow entries)"
    else
      echo "B3: OFF"
    fi
    ;;

  *) echo "usage: $0 {on|off|status}" >&2; exit 2 ;;
esac
