#!/usr/bin/env bash
# Cloudflare hardening step B3 — make the origin refuse non-Cloudflare traffic on the APEX
# HTTPS vhosts, so a scraper can't bypass the WAF / rate limits by hitting 77.42.66.76 directly.
#
#   bash ops/cloudflare-lockdown.sh on      # apply, then SELF-VERIFY through Cloudflare
#   bash ops/cloudflare-lockdown.sh off     # remove (instant, one reload)
#   bash ops/cloudflare-lockdown.sh status
#
# ⚠️ WHY THIS MATCHES $realip_remote_addr AND NOT `allow`/`deny`
#    The obvious implementation — `allow <cf ranges>; deny all;` — TOOK BOTH SITES DOWN when it
#    was first tried (2026-07-22, ~40s outage). nginx's allow/deny evaluates $remote_addr AFTER
#    the real_ip module has rewritten it, and we deliberately set `real_ip_header
#    CF-Connecting-IP` in Part B so logs/rate-limits see real visitors. By the time allow/deny
#    ran, $remote_addr was the VISITOR's IP — never Cloudflare's — so it rejected everyone,
#    including legitimate traffic through the proxy. $realip_remote_addr keeps the true TCP peer.
#    DO NOT "simplify" this back to allow/deny.
#
# ⚠️ THIS CHANGES THE CLOUDFLARE ROLLBACK PROCEDURE.
#    Normally rolling Cloudflare back = grey-cloud the DNS record. With B3 on, grey-clouding
#    sends visitors straight to an origin that answers 403. **Rollback is TWO steps, in this
#    order: run `cloudflare-lockdown.sh off` FIRST, then grey-cloud.**
#
# What it deliberately does NOT touch:
#  - the `www.*` :443 vhosts — still DNS-only (grey) as of 2026-07-22, so restricting them would
#    403 real visitors typing "www.". They only `return 301` to the apex, so no content leaks.
#  - the :80 vhosts — they serve /.well-known/acme-challenge/ for Let's Encrypt renewal.
#  - CWP's webmail.noc / mail.noc / cpanel.noc / bare-IP vhosts (would lock the owner out).
set -euo pipefail

CONF=/etc/nginx/conf.d/noc.conf
GEO=/etc/nginx/conf.d/00-cloudflare-geo.conf   # 00- so it loads before the vhosts
ORIGIN_IP=77.42.66.76
MARK='cf-lockdown'

reload_or_revert() {
  local backup="$1"
  if nginx -t >/dev/null 2>&1; then systemctl reload nginx; return 0; fi
  echo "nginx -t FAILED — reverting $CONF" >&2
  cp -a "$backup" "$CONF"
  nginx -t >/dev/null 2>&1 && systemctl reload nginx
  return 1
}

# Self-check, scoped to what the SERVER can actually prove.
#
# ⚠️ Do NOT "improve" this by curling the site through Cloudflare from here. Cloudflare blocks
#    requests originating from this box's own datacenter IP (Bot Fight Mode / WAF), so that test
#    returns 403 whether B3 is on or OFF — it is a guaranteed false negative, and an earlier
#    version of this script auto-reverted a perfectly good config because of it. Confirmed
#    2026-07-22: with B3 OFF, `curl` from here through the edge returned 403 for both a default
#    and a browser User-Agent.
#
# The "does the site still serve through Cloudflare?" check must be run FROM OUTSIDE — see the
# operator step printed at the end.
verify_locally() {
  local geo_entries vhosts
  geo_entries=$(grep -cE '^\s+[0-9a-f]+[0-9a-f.:]*/' "$GEO" 2>/dev/null || echo 0)
  vhosts=$(grep -c "$MARK" "$CONF" 2>/dev/null || echo 0)
  echo "  geo map      : $geo_entries CIDR entries loaded"
  echo "  vhosts gated : $vhosts (expected 2)"
  # A known Cloudflare range must be present, else the map is empty/garbled and everything 403s.
  grep -q '173.245.48.0/20' "$GEO" || { echo "  ✗ Cloudflare ranges missing from the geo map" >&2; return 1; }
  [ "$vhosts" -eq 2 ] || { echo "  ✗ wrong number of gated vhosts" >&2; return 1; }
  nginx -t >/dev/null 2>&1 || { echo "  ✗ nginx config invalid" >&2; return 1; }
  echo "  ✓ config valid, ranges present, exactly the 2 apex vhosts gated"
}

case "${1:-status}" in
  on)
    # Regenerate the allow-list every enable so it's never applied against a stale range list.
    {
      echo "# Generated by ops/cloudflare-lockdown.sh — do not edit by hand."
      echo "# Keyed on \$realip_remote_addr (the TRUE TCP peer) — see the header comment."
      echo "geo \$realip_remote_addr \$cf_origin_ok {"
      echo "    default 0;"
      { curl -fsS https://www.cloudflare.com/ips-v4; echo; curl -fsS https://www.cloudflare.com/ips-v6; echo; } \
        | grep -v '^$' | sed 's/^/    /; s/$/ 1;/'
      echo "    127.0.0.1 1;"
      echo "    ${ORIGIN_IP} 1;"
      echo "}"
    } > "$GEO"
    chmod 644 "$GEO"
    echo "allow-list: $(grep -cE '^\s+[0-9a-f]' "$GEO") entries"

    BAK="${CONF}.bak-lockdown-$(date -u +%Y%m%dT%H%M%SZ)"
    cp -a "$CONF" "$BAK"
    if ! grep -q "$MARK" "$CONF"; then
      # `client_max_body_size 35m;` appears ONCE in each of the two apex :443 blocks and nowhere
      # else in this file — exactly the pair we want to restrict.
      sed -i "s|^\(    client_max_body_size 35m;\)\$|\1\n    if (\$cf_origin_ok = 0) { return 403; } # ${MARK}|" "$CONF"
      n=$(grep -c "$MARK" "$CONF" || true)
      if [ "$n" -ne 2 ]; then
        echo "expected 2 insertion points, got $n — reverting, nothing changed" >&2
        cp -a "$BAK" "$CONF"; exit 1
      fi
    fi
    reload_or_revert "$BAK" || exit 1

    if verify_locally; then
      echo "B3 ON — apex :443 accepts Cloudflare only (backup: $BAK)"
      echo
      echo "⚠️ NOW VERIFY FROM OUTSIDE THIS SERVER (a browser, or curl from your own machine):"
      echo "     https://newobour.com/   and   https://alsawarey.com/   must load."
      echo "   If they DON'T:  bash $0 off"
    else
      echo "SELF-CHECK FAILED — reverting, nothing left applied." >&2
      cp -a "$BAK" "$CONF"
      nginx -t >/dev/null 2>&1 && systemctl reload nginx
      exit 1
    fi
    ;;

  off)
    BAK="${CONF}.bak-unlock-$(date -u +%Y%m%dT%H%M%SZ)"
    cp -a "$CONF" "$BAK"
    sed -i "/${MARK}/d" "$CONF"
    reload_or_revert "$BAK" && echo "B3 OFF — origin reachable directly again (backup: $BAK)"
    ;;

  status)
    if grep -q "$MARK" "$CONF" 2>/dev/null; then
      echo "B3: ON ($(grep -c "$MARK" "$CONF") vhost(s) restricted, $(grep -cE '^\s+[0-9a-f]' "$GEO" 2>/dev/null || echo 0) allow entries)"
    else
      echo "B3: OFF"
    fi
    ;;

  *) echo "usage: $0 {on|off|status}" >&2; exit 2 ;;
esac
